services:
  - type: web
    name: ai-resume-generator
    env: node
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
    buildCommand: |
      npm ci --workspaces
      npm run -w frontend build
    startCommand: node backend/server.js
